package com.g1.onetargetsdk.model

import androidx.annotation.Keep

@Keep
data class JsonContentX(
    val activeType: String? = null,
    val activeValue: Int? = null,
//    val audience: Any,
    val backgroundImage: String? = null,
    val buttonColor: String? = null,
    val buttonFontStyle: String? = null,
    val buttonFontWeight: String? = null,
    val buttonText: String? = null,
    val buttonTextColor: String? = null,
    val buttonUnderline: String? = null,
    val buttonUrl: String? = null,
    val canncelColor: String? = null,
    val closeType: String? = null,
    val closingAfter: Int? = null,
    val color: String? = null,
    val contentColor: String? = null,
    val contentFont: ContentFont? = null,
    val contentFontSize: ContentFontSize? = null,
    val contentFontStyle: String? = null,
    val contentFontWeight: String? = null,
    val contentText: String? = null,
    val contentTextAlign: String? = null,
    val contentUnderline: String? = null,
    val contentUrl: String? = null,
    val descriptionColor: String? = null,
    val descriptionFont: DescriptionFont? = null,
    val descriptionFontSize: DescriptionFontSize? = null,
    val descriptionFontStyle: String? = null,
    val descriptionFontWeight: String? = null,
    val descriptionText: String? = null,
    val descriptionTextAlign: String? = null,
    val descriptionUnderline: String? = null,
    val descriptionUrl: String? = null,
    val image: String? = null,
    val imageUrl: String? = null,
//    val inputs: List<Any>,
    val isHasBackground: Boolean? = null,
    val isShowTemplate: Boolean? = null,
    val labelColor: String? = null,
    val labelFont: LabelFont? = null,
    val labelFontSize: LabelFontSize? = null,
    val labelFontStyle: String? = null,
    val labelFontWeight: String? = null,
    val labelText: String? = null,
    val labelTextAlign: String? = null,
    val labelUnderline: String? = null,
    val labelUrl: String? = null,
    val loading: Boolean? = null,
    val message: String? = null,
    val name: String? = null,
    val opacity: Int? = null,
    val templateName: String? = null,
) : java.io.Serializable
